#!/bin/bash

if [ 1 != $# ]; then
	echo "Usage: ucapk ***.apk"
	exit 1
fi

PACKAGE_BASE_NAME=$(basename $1 .apk)
DIR_NAME=$PACKAGE_BASE_NAME
PACKAGE_NAME=$PACKAGE_BASE_NAME.apk

rm -rf $DIR_NAME
mkdir $DIR_NAME
cp $1 $DIR_NAME/

cd $DIR_NAME
unzip $PACKAGE_NAME
rm $PACKAGE_NAME
