#!/bin/bash

if [ 1 != $# ]; then
	echo "Usage: ucrpm ***.rpm"
	exit 1
fi

PACKAGE_BASE_NAME=$(basename $1 .rpm)
DIR_NAME=$PACKAGE_BASE_NAME
PACKAGE_NAME=$PACKAGE_BASE_NAME.rpm

rm -rf $DIR_NAME
mkdir $DIR_NAME
cp $1 $DIR_NAME/

cd $DIR_NAME
rpm2cpio $PACKAGE_NAME | cpio -div
rm $PACKAGE_NAME
